### ISSUE TITLE
demo instance: can't connect

### ISSUE THREAD

**Issue by drzraf** [modoboa/modoboa#1232]
# Impacted versions
https://demo.modoboa.org/accounts/login/

# Steps to reproduce
Try to connect using the admin@demo.local/admin user

# Current behavior
`Error: Failed to create the directory that will contain PDF documents ([Errno 2] No such file or directory: '/var/lib/modoboa/pdf_credentials')`

# Expected behavior
connexion happen

**Comment by tonioo** [comment]
Thank you for reporting this, it is fixed now.

**Comment by ilanmimoun** [comment]
Hello.
Sorry, but it's not fixed for me.
I have this error. How to fix it?
